apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: az-secret-store
spec:
  provider:
    azurekv:
      tenantId: "fb99af0e-66a0-4583-bdcf-594f960dff47"
      vaultUrl: "https://homelab-key.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret

