apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-secret
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden-admin-token
