apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc-longhorn
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi

