apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc-longhorn-bk
  namespace: apps
spec:
  volumeName: vaultwarden-backup
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
