apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  targetNamespace: longhorn-system
  releaseName: longhorn
  interval: 20m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3  
  chart:
    spec:
      chart: longhorn
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
    longhornUI:
      enabled: true
      replicas: 1
    defaultBackupStore:
      backupTarget: "nfs://10.179.4.213:/mnt/main/k8s-pv/longhorn-backup"
