apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: couchdb-ingress
  namespace: database
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`couchdb.ysonsbaolab.dev`)
      kind: Rule
      services:
        - name: couchdb-svc-couchdb
          port: 5984
  tls:
    secretName: couchdb-certificate-secret
