apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
  namespace: database
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-store # This references your ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: couchdb-couchdb
    creationPolicy: Owner
  data:
    - secretKey: couchdb-secret
      remoteRef:
        key: couchdb-creds
