apiVersion: v1
kind: Secret
metadata:
  name: couchdb-admin-secret
  namespace: database
stringData:
  adminUsername: "admin"
  adminPassword: "super-password"
  cookieAuthSecret: "random-cookie-secret"
