apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-helmrelease
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "3.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    service:
      annotations:
        tailscale.com/expose: "true"
    ingressRoute:
      dashboard:
        enabled: true

