apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    service:
      annotations:
        tailscale.com/expose: "true"
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.kubernetescrd"
      - "--providers.kubernetesingress"
    tlsStore:
      default:
        defaultCertificate:
          secretName: traefik-default-cert

