apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: traefik
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

