apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/the-big-ship/apps/infrastructure/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system

