apiVersion: v1
kind: Secret
metadata:
  name: traefik-values
  namespace: traefik
stringData:
  values.yaml: |
    additionalArguments:
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      # Enable ACME with Cloudflare DNS challenge:
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=your-email@example.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
    deployment:
      extraEnv:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-secret
              key: CF_API_TOKEN
    # Override the default TLS store so no default certificate is expected:
    tlsStore:
      default:
        defaultCertificate: {}

