apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-ingress
  namespace: traefik-system
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: vaultwarden-db-service
          port: 5432
  tls:
    passthrough: true

