apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-db-service
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: vaultwarden-db
