apiVersion: batch/v1
kind: CronJob
metadata:
  name: descheduler
  namespace: kube-system
spec:
  schedule: "*/30 * * * *" # Run every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: descheduler-sa
          restartPolicy: OnFailure
          containers:
            - name: descheduler
              image: registry.k8s.io/descheduler/descheduler:v0.34.0
              args:
                - "descheduler"
                - "--policy-config-file=/policy-dir/policy.yaml"
              volumeMounts:
                - name: policy-volume
                  mountPath: /policy-dir
          volumes:
            - name: policy-volume
              configMap:
                name: descheduler-policy
