apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pfsense-ingress-certificate
  namespace: traefik-system
spec:
  secretName: pfsense-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pfsense.ysonsbaolab.dev

---
apiVersion: v1
kind: Service
metadata:
  name: pfsense-service
  namespace: traefik-system
spec:
  type: ExternalName
  ports:
    - name: http
      port: 80
      targetPort: 80
  externalName: 10.8.8.1
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pfsense-ingress
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pfsense.ysonsbaolab.dev`)
      kind: Rule
      services:
        - name: pfsense-service
          port: 80
  tls:
    secretName: pfsense-certificate-secret
