apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-ingress-certificate
  namespace: apps
spec:
  secretName: pihole-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pihole.ysonsuperhomelab.com

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: apps
spec:
  type: ExternalName
  ports:
    - name: http
      port: 80
      targetPort: 80
  externalName: 10.8.8.8
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.ysonsuperhomelab.com`)
      kind: Rule
      services:
        - name: pihole-service
          port: 80
  tls:
    secretName: pihole-certificate-secret
