apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-ingress-certificate
  namespace: apps
spec:
  secretName: plex-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - plex.ysonsbaolab.dev

---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: apps
spec:
  type: ExternalName
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  externalName: 10.8.8.3
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.ysonsbaolab.dev`)
      kind: Rule
      services:
        - name: plex-service
          port: 32400
  tls:
    secretName: plex-certificate-secret
