apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox-cert-verification
  namespace: traefik-system
spec:
  secretName: proxmox-cert-verification-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - proxmox.ysonsuperhomelab.com
---
# Step 1: Endpoints for Proxmox (raw IP target)
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 10.8.8.2
    ports:
      - port: 8006
---
# Step 2: Headless Service to bind to the Endpoints
apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: traefik-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: proxmox
      port: 8006
      targetPort: 8006
---
# Step 3: IngressRouteTCP to forward raw TLS to Proxmox
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: proxmox-ingress
  namespace: traefik-system
spec:
  entryPoints:
    - proxmox
  routes:
    - match: HostSNI(`proxmox.ysonsuperhomelab.com`)
      services:
        - name: proxmox-service
          port: 8006
