apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox-ingress-certificate
  namespace: traefik-system
spec:
  secretName: proxmox-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - proxmox.ysonsuperhomelab.com

---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: traefik-system
spec:
  type: ExternalName
  ports:
    - name: http
      port: 8006
      targetPort: 8006
  externalName: 10.8.8.2
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ingress
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxmox.ysonsuperhomelab.com`)
      kind: Rule
      services:
        - name: proxmox-service
          port: 8006
  tls:
    secretName: proxmox-certificate-secret
