apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox-ingress-certificate
  namespace: apps
spec:
  secretName: proxmox-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - proxmox.ysonsuperhomelab.com

---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: apps
spec:
  type: ExternalName
  ports:
    - name: https
      port: 80 # Doesnt matter, use by traefik
      targetPort: 8006
  externalName: 10.8.8.2
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxmox.ysonsuperhomelab.com`)
      kind: Rule
      services:
        - name: proxmox-service
          port: 80 # need to match the service one
          serversTransport: proxmox-transport
  tls:
    secretName: proxmox-certificate-secret

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-transport
  namespace: apps
spec:
  insecureSkipVerify: true
