apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-ingress-certificate
  namespace: apps
spec:
  secretName: uptime-kuma-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - uptime-kuma.ysonsbaolab.dev

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: apps
spec:
  type: ExternalName
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  externalName: 10.8.8.12
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`uptime-kuma.ysonsbaolab.dev`)
      kind: Rule
      services:
        - name: uptime-kuma-service
          port: 3001
  tls:
    secretName: uptime-kuma-certificate-secret
