apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    defaultBackupStore:
      backupTarget: "nfs://10.8.8.3:/mnt/main/k8s-pv/longhorn-backup"
