apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
data:
  services.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/services/
    # https://simpleicons.org/

    - Home:
        - Proxmox:
            href: https://proxmox.ysonsuperhomelab.com
            description: Little router boii
            icon: si-proxmox-#E57000

        - Pihole:
            href: https://pihole.ysonsuperhomelab.com/admin/
            description: Super AD blocker!!
            icon: si-pihole-#96060C
            widget:
                type: pihole
                url: https://10.8.8.8/
                version: 6
                key: z/g9Ic3f0cYmOKeYVOq21dw//pI1E5QsVtYGav8ZvWs= 

        - TrueNAS:
            href: https://truenas.ysonsuperhomelab.com
            description: Manage your server with TrueNAS
            icon: si-truenas-#1A5E97

        - Vaultwarden:
            href: https://vaultwarden.ysonsuperhomelab.com
            description: Password manager for all your needs
            icon: si-vaultwarden-#000000

        - n8n:
            href: https://n8n.ysonsuperhomelab.com
            description: Automation cheating
            icon: si-n8n-#EA4B71

        - Grafana:
            href: https://grafana.ysonsuperhomelab.com
            description: Amazing dashboard
            icon: si-grafana-#F46800

        - Immich:
            href: http://piserver:2283
            description: FREE photo backup
            icon: si-immich-#4250AF

        - Plex:
            href: http://piserver:32400
            description: Amazing FREE MOIVES!!!
            icon: si-plex-#EBAF00

        - Traefik:
            href: http://traefik.ysonsuperhomelab.com
            description: Super network controller!!
            icon: si-traefik-#FFD800

        - Open Media Vault:
            href: http://piserver
            description: Manage your server with Open Media Vault
            icon: si-openmediavault-#5DACDF

    - Website:
        - EdinUni:
            href: https://www.learn.ed.ac.uk/ultra/course
            description: Super hogwarts shit!!
            icon: si-gitbook-#0E39A9
        - Github:
            href: https://www.github.com/ysonC
            description: The dumpling factory!!!
            icon: si-github-#181717
        - Blog:
            href: https://blog.ysonsuperhomelab.com
            description: My super fun blog!!
            icon: si-nginx-#009639
