# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: learning-db
  namespace: apps
spec:
  description: PostgreSQL cluster for Learing
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 2

  storage:
    size: 1Gi
    storageClass: local-path  # Use Rancher Local Path Storage

  bootstrap:
    initdb:
      database: learning
      owner: admin
      secret:
        name: learning-db-creds

  resources:
    requests:
      memory: 500Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

