apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: database
spec:
  description: PostgreSQL cluster for Immich
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 2
  podTemplate:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

  storage:
    size: 1Gi
    storageClass: nfs-client

  bootstrap:
    initdb:
      database: immich
      owner: admin # Must match the username in the secret
      secret:
        name: immich-db-creds

  resources:
    requests:
      memory: 500Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
