apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: database
spec:
  description: PostgreSQL cluster for Immich
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  instances: 2

  managed:
    roles:
      - name: admin
        superuser: true
        login: true

  storage:
    size: 4Gi
    storageClass: nfs-client

  bootstrap:
    initdb:
      database: immich
      owner: admin # Must match the username in the secret
      secret:
        name: immich-db-creds

  resources:
    requests:
      memory: 500Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
