apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: database
spec:
  description: PostgreSQL cluster for Immich
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.14
  instances: 1
  postgresql:
    shared_preload_libraries:
      - vchord.so

  managed:
    roles:
      - name: admin
        superuser: true
        login: true

  storage:
    size: 4Gi
    storageClass: nfs-client

  bootstrap:
    initdb:
      database: immich
      owner: admin # Must match the username in the secret
      secret:
        name: immich-db-creds
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;

  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 2
