apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
  namespace: cnpg-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/nas/k8s-pg/immich
    server: 10.179.4.213

