apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n
          ports:
            - containerPort: 5678
          env:
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "n8n"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "n8n"
            - name: GENERIC_TIMEZONE
              value: "Asia/Tokyo"
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: WEBHOOK_URL
              value: "https://10.8.8.51:32567"
