apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: apps
spec:
  replicas: 3
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: n8n-pvc-longhorn
              mountPath: /data
      containers:
        - name: n8n
          image: n8nio/n8n
          command: ["/bin/sh"]
          args: ["-c", "sleep 5; n8n start"]
          ports:
            - containerPort: 5678
          env:
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "n8n"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "n8n"
            - name: GENERIC_TIMEZONE
              value: "Europe/London"
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: WEBHOOK_URL
              value: "https://n8n.ysonsuperhomelab.com"
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - name: n8n-pvc-longhorn
              mountPath: /home/node/.n8n
      restartPolicy: Always
      volumes:
        - name: n8n-pvc-longhorn
          persistentVolumeClaim:
            claimName: n8n-pvc-longhorn
