apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc-longhorn
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
