apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc-longhorn-bk
  namespace: apps
spec:
  volumeName: n8n-backup
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
