apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudfared-tunnel-token
  namespace: networking
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: obsidian-tunnel-cloudflared-token
