apiVersion: v1
kind: Service
metadata:
  name: glance-service
  namespace: apps
spec:
  type: NodePort
  selector:
    app: glance
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31888
