apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
spec:
  acme:
    disableAccountKeyGeneration: true
    email: wyson002@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory # Use Production Server
