apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager/

patches:
  - path: cert-issuer-patch.yaml
    target:
      kind: ClusterIssuer
      name: cloudflare-cluster-issuer
      namespace: cert-manager
