apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-ingress-certificate
  namespace: apps
spec:
  secretName: blog-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - blog.ysonsbaolab.dev

