apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: database-ingress-certificate
  namespace: database
spec:
  secretName: database-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - database.ysonsuperhomelab.com


