apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-ingress-certificate
  namespace: apps
spec:
  secretName: glance-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - glance.ysonsbaolab.dev
