apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ingress-certificate
  namespace: monitoring
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.ysonsbaolab.dev
