apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-ingress-certificate
  namespace: apps
spec:
  secretName: homepage-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - homepage.ysonsbaolab.dev


