apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-ingress-certificate
  namespace: apps
spec:
  secretName: immich-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - immich.ysonsuperhomelab.com
