apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ingress-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.ysonsbaolab.dev
