apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-ingress-certificate
  namespace: apps
spec:
  secretName: n8n-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.ysonsuperhomelab.com
