apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-ingress-certificate
  namespace: apps
spec:
  secretName: traefik-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - traefik.ysonsbaolab.dev
