apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/the-big-ship/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
