apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: db-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: ./database/the-big-ship
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-kustomization
