apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: instrastructure-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/the-big-ship
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
