apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Service listens on port 80 inside the cluster
      targetPort: 80    # Forwards to container's port 80
      nodePort: 32080   # Exposes on Raspberry Pi’s port 32080
  type: NodePort        # Makes the service externally accessible

