apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-csi-driver
  namespace: flux-system
spec:
    interval: 24h
    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
