apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml  # Ensure service.yaml is listed here
  #- ingress.yaml  # (Optional) Ensure other resources are here too

