---
- name: Copy K3s kubeconfig to local machine
  hosts: master
  gather_facts: false
  tasks:
    - name: Fetch kubeconfig from master
      become: yes
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/tmp/k3s_{{ inventory_hostname }}.yaml"
        flat: yes

- name: Setup kubeconfig locally
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure .kube directory exists locally
      file:
        path: "{{ lookup('env', 'HOME') }}/.kube"
        state: directory
        mode: "0755"

    - name: Update kubeconfig server address with master IP
      lineinfile:
        path: "/tmp/k3s_captain.yaml"
        regexp: '(^\s*server:\s*https://).*(:6443)'
        line: "    server: https://{{ hostvars['captain']['ansible_host'] }}:6443"

    - name: Copy updated kubeconfig to user's .kube/config
      copy:
        src: "/tmp/k3s_captain.yaml"
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        mode: "0600"
