- name: Prune unused container images on all K3s nodes
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Run k3s image prune (ignore timeout errors)
      ansible.builtin.command: k3s crictl rmi --prune
      register: result
      ignore_errors: true
      changed_when: "'Deleted:' in (result.stdout or '')"

    - name: Show prune output
      ansible.builtin.debug:
        var: result.stdout_lines
