---
- name: Reboot K3s Master Node
  hosts: master
  become: yes
  tasks:
    - name: Ensure K3s server starts on boot
      systemd:
        name: k3s
        enabled: yes

    - name: Stop K3s server before reboot
      systemd:
        name: k3s
        state: stopped

    - name: Reboot master node
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: whoami

- name: Reboot K3s Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Ensure K3s agent starts on boot
      systemd:
        name: k3s-agent
        enabled: yes

    - name: Stop K3s agent before reboot
      systemd:
        name: k3s-agent
        state: stopped

    - name: Reboot worker node
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: whoami
