apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.179.5.96
    path: "/srv/dev-disk-by-uuid-5d9f109b-e277-4117-973e-c7e67e8422ab/picluster/homepage"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homepage-pv

