apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  selector:
    app: homepage
  ports:
  - port: 3000         # The port the container is listening on
    targetPort: 3000   # Maps to container port
    nodePort: 30900    # Accessible on <NodeIP>:30900
  type: NodePort       # Exposes the service on a static port on each Node
