apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "15.5.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: "admin"
      password: "your-secure-password"
      database: "homelab"
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: "nfs"

