apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "15.5.0"
      sourceRef:
        kind: HelmRepository
        name: postgresql-repo
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 17.4.0-debian-12-r2
    architecture: standalone
    auth:
      username: "admin"
      password: "your-secure-password"
      database: "postgres"
    replication:
      enabled: true
    primary:
      podSecurityContext:
        enabled: true
        fsGroup: 1001
      persistence:
        enabled: true
        size: 5Gi
        storageClass: "nfs"
    replica:
      podSecurityContext:
        enabled: true
        fsGroup: 1001
      persistence:
        enabled: true
        size: 5Gi
        storageClass: "nfs"
    service:
      type: ClusterIP
      ports:
        postgresql: 5432
