apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-ingress
  namespace: database
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`database.ysonsuperhomelab.com`)
      services:
        - name: postgresql
          port: 5432
  tls:
    secretName: postgres-certificate-secret
