apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/ysonC/super-homelab.git
  ref:
    branch: main

