apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hugo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hugo-image
  policy:
    semver:
      range: 0.0.x
