apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: hugo-auto-update
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab
  git:
    commit:
      author:
        name: fluxcd
        email: fluxcd@dumplingfactory.com
    push:
      branch: main
  update:
    path: ./
