---
- name: Install K3s on master (if not already installed)
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ K3S_VERSION }} INSTALL_K3S_EXEC="{{ INSTALL_K3S_EXEC }}" sh -
  args:
    executable: /bin/bash

- name: Retrieve K3s Token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: Fetch kubeconfig from master
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/tmp/k3s_{{ inventory_hostname }}.yaml"
    flat: yes

- name: Update kubeconfig server address with master IP
  delegate_to: localhost
  become: no
  lineinfile:
    path: "/tmp/k3s_{{ inventory_hostname }}.yaml"
    regexp: '(^\s*server:\s*https://).*(:6443)'
    line: "    server: https://{{ hostvars[inventory_hostname]['ansible_host'] }}:6443"

- name: Copy updated kubeconfig to user's home
  delegate_to: localhost
  become: no
  copy:
    src: "/tmp/k3s_{{ inventory_hostname }}.yaml"
    dest: "{{ lookup('env','HOME') }}/.kube/config"
    mode: "0600"
