apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  targetNamespace: cnpg-system
  releaseName: cnpg
  interval: 20m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
