apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nfs-storageclass/
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nfs-client-provisioner
