apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres-pvc-longhorn
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
