# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/traefik.io/ingressroute_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.ysonsuperhomelab.com`)
      kind: Rule
      services:
        - name: homepage-service
          port: 3000
  tls:
      secretName: homepage-certificate-secret
