apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ai-agent-view
  - blog
  - default
  - external-service
  - glance
  - immich
  - n8n
  - paperless
  - test
  - vaultwarden
  - vaultwarden-testing
