---
- name: Setup K3s Master Node with Tailscale
  hosts: master
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - common
    - master

- name: Setup K3s Worker Nodes
  hosts: workers
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - common
    - worker
