apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/monitoring/

patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
      name: prometheus-stack
      namespace: monitoring
