apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  values:
    server:
      retention: "7d"
      presistentVolume:
        enabled: true
        size: "10Gi"
        accessModes: 
         - ReadWriteOnce
        storageClass: "longhorn"
    alertmanager:
      enabled: true
      persistentVolume:
        enabled: true
        size: 500Mi
