apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  values:
    server:
      retention: "7d"
      global:
        scrape_interval: 5m
        scrape_timeout: 30s
        evaluation_interval: 5m
