# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  values:
    prometheus:
      enabled: true 
      prometheusSpec:
        retention: 7d
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        persistentVolumeClaimRetentionPolicy: 
          whenDeleted: Retain
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi

    alertmanger:
      alertmanagerSpec:
        retention: 120h
        persistentVolumeClaimRetentionPolicy:   
          whenDeleted: Retain
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: 
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi

    grafana:
      adminPassword: "admin"
      persistentVolumeClaimRetentionPolicy: 
        whenDeleted: Retain
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 500Mi
