apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.ysonsuperhomelab.com`)
      kind: Rule
      services:
        - name: homepage-service
          port: 3000
  tls:
    certResolver: cloudflare

