apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
metadata:
  name: homepage-kustomization
  namespace: flux-system
spec:
  resources:
    - deployment.yaml
    - service.yaml
    - persistent_storage.yaml
  prune: true

