apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-url-secret
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv-store # This references your ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: immich-db-url
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: immich-db-url # The key name as stored in your external vault
