apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: apps
spec:
  targetNamespace: apps
  releaseName: immich
  interval: 20m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  values:
    image:
      tag: v1.134.0

    immich:
      persistence:
        library:
          existingClaim: immich-pvc-nfs

    server:
      enabled: true
      replicaCount: 2
      env:
        - name: IMMICH_WORKERS_INCLUDE
          value: "api"
        - name: REDIS_HOSTNAME
          value: immich-redis-master
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

    envFrom:
      - secretRef:
          name: immich-db-url

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false

    machine-learning:
      enabled: true
      replicaCount: 2
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        pullPolicy: IfNotPresent
      env:
        TRANSFORMERS_CACHE: /cache
      resources:
        requests:
          cpu: 0.2
          memory: 512Mi
        limits:
          cpu: 1.0
          memory: 1Gi
