apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.ysonsuperhomelab.com`)
      kind: Rule
      services:
        - name: immich-server
          port: 2283
  tls:
    secretName: immich-certificate-secret
