apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-workers
  namespace: apps
  labels:
    app: immich
    role: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
      role: workers
  template:
    metadata:
      labels:
        app: immich
        role: workers
    spec:
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:v1.134.0
          env:
            - name: IMMICH_WORKERS_EXCLUDE
              value: "api"
            - name: REDIS_HOSTNAME
              value: immich-redis-master
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: immich-db-url
                  key: DB_URL
            - name: DB_HOSTNAME
              value: "{{ .Release.Name }}-postgresql"
            - name: DB_USERNAME
              value: "{{ .Values.postgresql.global.postgresql.auth.username }}"
            - name: DB_DATABASE_NAME
              value: "{{ .Values.postgresql.global.postgresql.auth.database }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgresql.global.postgresql.auth.password }}"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
