apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc-nfs
  namespace: apps
spec:
  storageClassName: nfs-client
  volumeName: immich-pvc-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
