apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc-nfs
  namespace: apps
spec:
  storageClassName: nfs-client
  volumeName: pvc-5a3d7aae-614d-4eb5-9529-8dbc2801bc94
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
