immich:
  persistence:
    library:
      enabled: true
      size: 100Gi
      storageClass: nfs-client
      accessMode: ReadWriteOnce

  server:
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: photos.example.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - photos.example.com
            secretName: immich-tls

  envFrom:
    - secretRef:
        name: immich-db-url

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: nfs-client
      size: 1Gi
