image:
  tag: v1.119.0

immich:
  persistence:
    library:
      existingClaim: immich-pvc-nfs

server:
  enabled: true
  replicaCount: 2
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

envFrom:
  - secretRef:
      name: immich-db-url

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
