image:
  tag: v1.119.0

immich:
  persistence:
    library:
      existingClaim: immich-pvc-nfs

server:
  enabled: true
  replicaCount: 2
  env:
    - name: IMMICH_WORKERS_INCLUDE
      value: "api"
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

microservices:
  enabled: true
  replicaCount: 1 # keep metadata workers small/slower
  env:
    - name: IMMICH_WORKERS_EXCLUDE
      value: "api" # only run background jobs here
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

envFrom:
  - secretRef:
      name: immich-db-url
env:
  REDIS_HOSTNAME: immich-redis-master

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
