image:
  tag: v1.119.0

immich:
  persistence:
    library:
      existingClaim: immich-pvc-nfs

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent

envFrom:
  - secretRef:
      name: immich-db-url

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
