image:
  tag: v1.119.0

immich:
  persistence:
    library:
      existingClaim: immich-pvc-nfs

  server:
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
        hosts:
          - host: photos.example.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - photos.example.com
            secretName: immich-tls

  envFrom:
    - secretRef:
        name: immich-db-url

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
