apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "57.10.0" 
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    ## ----------------------------------------------------
    ## Prometheus Operator + CRDs
    ## ----------------------------------------------------
    crds:
      enabled: true

    prometheusOperator:
      enabled: true
      admissionWebhooks:
        enabled: true

    ## ----------------------------------------------------
    ## Prometheus server config
    ## (prometheusSpec override the Operator-based settings)
    ## ----------------------------------------------------
    prometheus:
      enabled: true
      prometheusSpec:
        image:
          registry: quay.io
          repository: prometheus/prometheus
          tag: v2.43.0
        replicas: 1
        retention: "7d"
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi

    ## ----------------------------------------------------
    ## Alertmanager
    ## (Uses alertmanagerSpec for Operator-based config)
    ## ----------------------------------------------------
    alertmanager:
      enabled: true
      alertmanagerSpec:
        image:
          registry: quay.io
          repository: prometheus/alertmanager
          tag: v0.26.0
        replicas: 1
        retention: 120h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 1Gi

    ## ----------------------------------------------------
    ## Grafana config
    ## (Corresponds to the embedded grafana subchart values)
    ## ----------------------------------------------------
    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 9.5.2
      adminPassword: "admin"
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 500Mi
