apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "55.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    server:
      image:
        repository: quay.io/prometheus/prometheus
        tag: latest
        pullPolicy: IfNotPresent

    kube-state-metrics:
      enabled: true

    prometheus-node-exporter:
      enabled: true
      rbac:
        pspEnabled: false
      containerSecurityContext:
        allowPrivilegeEscalation: false

    prometheus-pushgateway:
      enabled: true
      serviceAnnotations:
        prometheus.io/probe: pushgateway

    grafana:
      adminPassword: admin
      service:
        type: ClusterIP
