apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.3.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    ## ----------------------------------------------------
    ## Prometheus Operator + CRDs
    ## ----------------------------------------------------
    crds:
      enabled: true

    prometheusOperator:
      enabled: true
      admissionWebhooks:
        enabled: true

    ## ----------------------------------------------------
    ## Prometheus server config
    ## (prometheusSpec override the Operator-based settings)
    ## ----------------------------------------------------
    prometheus:
      enabled: true
      prometheusSpec:
        image:
          registry: quay.io
          repository: prometheus/prometheus
          tag: v2.43.0
        replicas: 1
        retention: "7d"

    ## ----------------------------------------------------
    ## Alertmanager
    ## (Uses alertmanagerSpec for Operator-based config)
    ## ----------------------------------------------------
    alertmanager:
      enabled: true
      alertmanagerSpec:
        image:
          registry: quay.io
          repository: prometheus/alertmanager
          tag: v0.26.0
        replicas: 1

    ## ----------------------------------------------------
    ## Grafana config
    ## (Corresponds to the embedded grafana subchart values)
    ## ----------------------------------------------------
    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 9.5.2
      adminPassword: "admin"
