apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.ysonsbaolab.dev`)
      kind: Rule
      services:
        - name: prometheus-stack-grafana
          port: 80
  tls:
    secretName: grafana-certificate-secret
